# Generated by Django 4.2.7 on 2023-11-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill_remove_freelancerprofile_skills_and_more'),
        ('listings', '0002_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
