# Generated by Django 4.2.7 on 2023-11-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_email',
            field=models.EmailField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_name',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_communication',
            field=models.CharField(choices=[('email', 'Email'), ('chat', 'Chat'), ('phone', 'Phone')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
